version: "3.8"
services:
  front:
    container_name: front

    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - node_modules_volume:/front/node_modules

    command: sh -c "npm start"

    ports:
      - "3001:3000"
volumes:
  node_modules_volume:
